# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn13', models.CharField(db_column='ISBN13', max_length=14, primary_key=True, serialize=False)),
                ('isbn10', models.CharField(db_column='ISBN10', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('years', models.IntegerField()),
                ('num_copies', models.IntegerField()),
                ('price', models.FloatField()),
                ('book_format', models.CharField(max_length=9)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('book_subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('login_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('login_password', models.CharField(max_length=255)),
                ('credit_card', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=255)),
                ('phone_num', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('review_text', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shoppingcart',
                'managed': False,
            },
        ),
    ]
