# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn13', models.CharField(db_column='ISBN13', max_length=14, primary_key=True, serialize=False)),
                ('isbn10', models.CharField(db_column='ISBN10', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('num_copies', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('book_format', models.CharField(blank=True, max_length=9, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('book_subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('login_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('login_password', models.CharField(max_length=255)),
                ('credit_card', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedbacks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rates',
                'managed': False,
            },
        ),
    ]
