# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn13', models.CharField(db_column='ISBN13', max_length=14, primary_key=True, serialize=False)),
                ('isbn10', models.CharField(db_column='ISBN10', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('years', models.IntegerField()),
                ('num_copies', models.IntegerField()),
                ('price', models.FloatField()),
                ('book_format', models.CharField(max_length=9)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('book_subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=255)),
                ('isbn13', models.ForeignKey(db_column='ISBN13', on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Book')),
                ('login_name', models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(default='', max_length=16)),
                ('mailing_address', models.TextField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('review_text', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('isbn13', models.ForeignKey(db_column='ISBN13', on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Book')),
                ('login_name', models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('isbn13', models.ForeignKey(db_column='ISBN13', on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Book')),
                ('login_name', models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='isbn13',
            field=models.ForeignKey(db_column='ISBN13', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_isbn13_requests_created', to='bookstore.Review'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rated',
            field=models.ForeignKey(db_column='rated', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_rated_requests_created', to='bookstore.Review'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rater',
            field=models.ForeignKey(db_column='rater', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_rater_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('login_name', 'isbn13')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('login_name', 'isbn13')]),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('rater', 'rated', 'isbn13')]),
        ),
        migrations.AlterUniqueTogether(
            name='customerorder',
            unique_together=set([('login_name', 'isbn13')]),
        ),
    ]
