# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='CustomerOrder',
        ),
        migrations.AlterModelTable(
            name='customerorder',
            table='customer_order',
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table='shopping_cart',
        ),
    ]
