# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0002_auto_20161125_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(default='', max_length=16)),
                ('mailing_address', models.TextField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profile',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='login_name',
            field=models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rater',
            field=models.ForeignKey(db_column='rater', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_rater_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='login_name',
            field=models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='login_name',
            field=models.ForeignKey(db_column='login_name', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
