# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20161130_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerorder',
            unique_together=set([]),
        ),
    ]
