# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20161204_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=9),
        ),
    ]
