# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20161125_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Profile',
            options={},
        ),
    ]
