# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20161125_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
